	q_sys u0 (
		.alt_xcvr_reconfig_0_mgmt_clk_clk_clk                   (<connected-to-alt_xcvr_reconfig_0_mgmt_clk_clk_clk>),                   //       alt_xcvr_reconfig_0_mgmt_clk_clk.clk
		.alt_xcvr_reconfig_0_mgmt_rst_reset_reset               (<connected-to-alt_xcvr_reconfig_0_mgmt_rst_reset_reset>),               //     alt_xcvr_reconfig_0_mgmt_rst_reset.reset
		.alt_xcvr_reconfig_0_reconfig_mgmt_address              (<connected-to-alt_xcvr_reconfig_0_reconfig_mgmt_address>),              //      alt_xcvr_reconfig_0_reconfig_mgmt.address
		.alt_xcvr_reconfig_0_reconfig_mgmt_read                 (<connected-to-alt_xcvr_reconfig_0_reconfig_mgmt_read>),                 //                                       .read
		.alt_xcvr_reconfig_0_reconfig_mgmt_readdata             (<connected-to-alt_xcvr_reconfig_0_reconfig_mgmt_readdata>),             //                                       .readdata
		.alt_xcvr_reconfig_0_reconfig_mgmt_waitrequest          (<connected-to-alt_xcvr_reconfig_0_reconfig_mgmt_waitrequest>),          //                                       .waitrequest
		.alt_xcvr_reconfig_0_reconfig_mgmt_write                (<connected-to-alt_xcvr_reconfig_0_reconfig_mgmt_write>),                //                                       .write
		.alt_xcvr_reconfig_0_reconfig_mgmt_writedata            (<connected-to-alt_xcvr_reconfig_0_reconfig_mgmt_writedata>),            //                                       .writedata
		.clk_0_clk_clk                                          (<connected-to-clk_0_clk_clk>),                                          //                              clk_0_clk.clk
		.clk_0_clk_reset_reset_n                                (<connected-to-clk_0_clk_reset_reset_n>),                                //                        clk_0_clk_reset.reset_n
		.master_read_control_fixed_location                     (<connected-to-master_read_control_fixed_location>),                     //                    master_read_control.fixed_location
		.master_read_control_read_base                          (<connected-to-master_read_control_read_base>),                          //                                       .read_base
		.master_read_control_read_length                        (<connected-to-master_read_control_read_length>),                        //                                       .read_length
		.master_read_control_go                                 (<connected-to-master_read_control_go>),                                 //                                       .go
		.master_read_control_done                               (<connected-to-master_read_control_done>),                               //                                       .done
		.master_read_control_early_done                         (<connected-to-master_read_control_early_done>),                         //                                       .early_done
		.master_read_user_read_buffer                           (<connected-to-master_read_user_read_buffer>),                           //                       master_read_user.read_buffer
		.master_read_user_buffer_output_data                    (<connected-to-master_read_user_buffer_output_data>),                    //                                       .buffer_output_data
		.master_read_user_data_available                        (<connected-to-master_read_user_data_available>),                        //                                       .data_available
		.master_write_control_fixed_location                    (<connected-to-master_write_control_fixed_location>),                    //                   master_write_control.fixed_location
		.master_write_control_write_base                        (<connected-to-master_write_control_write_base>),                        //                                       .write_base
		.master_write_control_write_length                      (<connected-to-master_write_control_write_length>),                      //                                       .write_length
		.master_write_control_go                                (<connected-to-master_write_control_go>),                                //                                       .go
		.master_write_control_done                              (<connected-to-master_write_control_done>),                              //                                       .done
		.master_write_user_write_buffer                         (<connected-to-master_write_user_write_buffer>),                         //                      master_write_user.write_buffer
		.master_write_user_buffer_input_data                    (<connected-to-master_write_user_buffer_input_data>),                    //                                       .buffer_input_data
		.master_write_user_buffer_full                          (<connected-to-master_write_user_buffer_full>),                          //                                       .buffer_full
		.pcie_cv_hip_avmm_0_hip_ctrl_test_in                    (<connected-to-pcie_cv_hip_avmm_0_hip_ctrl_test_in>),                    //            pcie_cv_hip_avmm_0_hip_ctrl.test_in
		.pcie_cv_hip_avmm_0_hip_ctrl_simu_mode_pipe             (<connected-to-pcie_cv_hip_avmm_0_hip_ctrl_simu_mode_pipe>),             //                                       .simu_mode_pipe
		.pcie_cv_hip_avmm_0_hip_pipe_sim_pipe_pclk_in           (<connected-to-pcie_cv_hip_avmm_0_hip_pipe_sim_pipe_pclk_in>),           //            pcie_cv_hip_avmm_0_hip_pipe.sim_pipe_pclk_in
		.pcie_cv_hip_avmm_0_hip_pipe_sim_pipe_rate              (<connected-to-pcie_cv_hip_avmm_0_hip_pipe_sim_pipe_rate>),              //                                       .sim_pipe_rate
		.pcie_cv_hip_avmm_0_hip_pipe_sim_ltssmstate             (<connected-to-pcie_cv_hip_avmm_0_hip_pipe_sim_ltssmstate>),             //                                       .sim_ltssmstate
		.pcie_cv_hip_avmm_0_hip_pipe_eidleinfersel0             (<connected-to-pcie_cv_hip_avmm_0_hip_pipe_eidleinfersel0>),             //                                       .eidleinfersel0
		.pcie_cv_hip_avmm_0_hip_pipe_eidleinfersel1             (<connected-to-pcie_cv_hip_avmm_0_hip_pipe_eidleinfersel1>),             //                                       .eidleinfersel1
		.pcie_cv_hip_avmm_0_hip_pipe_eidleinfersel2             (<connected-to-pcie_cv_hip_avmm_0_hip_pipe_eidleinfersel2>),             //                                       .eidleinfersel2
		.pcie_cv_hip_avmm_0_hip_pipe_eidleinfersel3             (<connected-to-pcie_cv_hip_avmm_0_hip_pipe_eidleinfersel3>),             //                                       .eidleinfersel3
		.pcie_cv_hip_avmm_0_hip_pipe_powerdown0                 (<connected-to-pcie_cv_hip_avmm_0_hip_pipe_powerdown0>),                 //                                       .powerdown0
		.pcie_cv_hip_avmm_0_hip_pipe_powerdown1                 (<connected-to-pcie_cv_hip_avmm_0_hip_pipe_powerdown1>),                 //                                       .powerdown1
		.pcie_cv_hip_avmm_0_hip_pipe_powerdown2                 (<connected-to-pcie_cv_hip_avmm_0_hip_pipe_powerdown2>),                 //                                       .powerdown2
		.pcie_cv_hip_avmm_0_hip_pipe_powerdown3                 (<connected-to-pcie_cv_hip_avmm_0_hip_pipe_powerdown3>),                 //                                       .powerdown3
		.pcie_cv_hip_avmm_0_hip_pipe_rxpolarity0                (<connected-to-pcie_cv_hip_avmm_0_hip_pipe_rxpolarity0>),                //                                       .rxpolarity0
		.pcie_cv_hip_avmm_0_hip_pipe_rxpolarity1                (<connected-to-pcie_cv_hip_avmm_0_hip_pipe_rxpolarity1>),                //                                       .rxpolarity1
		.pcie_cv_hip_avmm_0_hip_pipe_rxpolarity2                (<connected-to-pcie_cv_hip_avmm_0_hip_pipe_rxpolarity2>),                //                                       .rxpolarity2
		.pcie_cv_hip_avmm_0_hip_pipe_rxpolarity3                (<connected-to-pcie_cv_hip_avmm_0_hip_pipe_rxpolarity3>),                //                                       .rxpolarity3
		.pcie_cv_hip_avmm_0_hip_pipe_txcompl0                   (<connected-to-pcie_cv_hip_avmm_0_hip_pipe_txcompl0>),                   //                                       .txcompl0
		.pcie_cv_hip_avmm_0_hip_pipe_txcompl1                   (<connected-to-pcie_cv_hip_avmm_0_hip_pipe_txcompl1>),                   //                                       .txcompl1
		.pcie_cv_hip_avmm_0_hip_pipe_txcompl2                   (<connected-to-pcie_cv_hip_avmm_0_hip_pipe_txcompl2>),                   //                                       .txcompl2
		.pcie_cv_hip_avmm_0_hip_pipe_txcompl3                   (<connected-to-pcie_cv_hip_avmm_0_hip_pipe_txcompl3>),                   //                                       .txcompl3
		.pcie_cv_hip_avmm_0_hip_pipe_txdata0                    (<connected-to-pcie_cv_hip_avmm_0_hip_pipe_txdata0>),                    //                                       .txdata0
		.pcie_cv_hip_avmm_0_hip_pipe_txdata1                    (<connected-to-pcie_cv_hip_avmm_0_hip_pipe_txdata1>),                    //                                       .txdata1
		.pcie_cv_hip_avmm_0_hip_pipe_txdata2                    (<connected-to-pcie_cv_hip_avmm_0_hip_pipe_txdata2>),                    //                                       .txdata2
		.pcie_cv_hip_avmm_0_hip_pipe_txdata3                    (<connected-to-pcie_cv_hip_avmm_0_hip_pipe_txdata3>),                    //                                       .txdata3
		.pcie_cv_hip_avmm_0_hip_pipe_txdatak0                   (<connected-to-pcie_cv_hip_avmm_0_hip_pipe_txdatak0>),                   //                                       .txdatak0
		.pcie_cv_hip_avmm_0_hip_pipe_txdatak1                   (<connected-to-pcie_cv_hip_avmm_0_hip_pipe_txdatak1>),                   //                                       .txdatak1
		.pcie_cv_hip_avmm_0_hip_pipe_txdatak2                   (<connected-to-pcie_cv_hip_avmm_0_hip_pipe_txdatak2>),                   //                                       .txdatak2
		.pcie_cv_hip_avmm_0_hip_pipe_txdatak3                   (<connected-to-pcie_cv_hip_avmm_0_hip_pipe_txdatak3>),                   //                                       .txdatak3
		.pcie_cv_hip_avmm_0_hip_pipe_txdetectrx0                (<connected-to-pcie_cv_hip_avmm_0_hip_pipe_txdetectrx0>),                //                                       .txdetectrx0
		.pcie_cv_hip_avmm_0_hip_pipe_txdetectrx1                (<connected-to-pcie_cv_hip_avmm_0_hip_pipe_txdetectrx1>),                //                                       .txdetectrx1
		.pcie_cv_hip_avmm_0_hip_pipe_txdetectrx2                (<connected-to-pcie_cv_hip_avmm_0_hip_pipe_txdetectrx2>),                //                                       .txdetectrx2
		.pcie_cv_hip_avmm_0_hip_pipe_txdetectrx3                (<connected-to-pcie_cv_hip_avmm_0_hip_pipe_txdetectrx3>),                //                                       .txdetectrx3
		.pcie_cv_hip_avmm_0_hip_pipe_txelecidle0                (<connected-to-pcie_cv_hip_avmm_0_hip_pipe_txelecidle0>),                //                                       .txelecidle0
		.pcie_cv_hip_avmm_0_hip_pipe_txelecidle1                (<connected-to-pcie_cv_hip_avmm_0_hip_pipe_txelecidle1>),                //                                       .txelecidle1
		.pcie_cv_hip_avmm_0_hip_pipe_txelecidle2                (<connected-to-pcie_cv_hip_avmm_0_hip_pipe_txelecidle2>),                //                                       .txelecidle2
		.pcie_cv_hip_avmm_0_hip_pipe_txelecidle3                (<connected-to-pcie_cv_hip_avmm_0_hip_pipe_txelecidle3>),                //                                       .txelecidle3
		.pcie_cv_hip_avmm_0_hip_pipe_txswing0                   (<connected-to-pcie_cv_hip_avmm_0_hip_pipe_txswing0>),                   //                                       .txswing0
		.pcie_cv_hip_avmm_0_hip_pipe_txswing1                   (<connected-to-pcie_cv_hip_avmm_0_hip_pipe_txswing1>),                   //                                       .txswing1
		.pcie_cv_hip_avmm_0_hip_pipe_txswing2                   (<connected-to-pcie_cv_hip_avmm_0_hip_pipe_txswing2>),                   //                                       .txswing2
		.pcie_cv_hip_avmm_0_hip_pipe_txswing3                   (<connected-to-pcie_cv_hip_avmm_0_hip_pipe_txswing3>),                   //                                       .txswing3
		.pcie_cv_hip_avmm_0_hip_pipe_txmargin0                  (<connected-to-pcie_cv_hip_avmm_0_hip_pipe_txmargin0>),                  //                                       .txmargin0
		.pcie_cv_hip_avmm_0_hip_pipe_txmargin1                  (<connected-to-pcie_cv_hip_avmm_0_hip_pipe_txmargin1>),                  //                                       .txmargin1
		.pcie_cv_hip_avmm_0_hip_pipe_txmargin2                  (<connected-to-pcie_cv_hip_avmm_0_hip_pipe_txmargin2>),                  //                                       .txmargin2
		.pcie_cv_hip_avmm_0_hip_pipe_txmargin3                  (<connected-to-pcie_cv_hip_avmm_0_hip_pipe_txmargin3>),                  //                                       .txmargin3
		.pcie_cv_hip_avmm_0_hip_pipe_txdeemph0                  (<connected-to-pcie_cv_hip_avmm_0_hip_pipe_txdeemph0>),                  //                                       .txdeemph0
		.pcie_cv_hip_avmm_0_hip_pipe_txdeemph1                  (<connected-to-pcie_cv_hip_avmm_0_hip_pipe_txdeemph1>),                  //                                       .txdeemph1
		.pcie_cv_hip_avmm_0_hip_pipe_txdeemph2                  (<connected-to-pcie_cv_hip_avmm_0_hip_pipe_txdeemph2>),                  //                                       .txdeemph2
		.pcie_cv_hip_avmm_0_hip_pipe_txdeemph3                  (<connected-to-pcie_cv_hip_avmm_0_hip_pipe_txdeemph3>),                  //                                       .txdeemph3
		.pcie_cv_hip_avmm_0_hip_pipe_phystatus0                 (<connected-to-pcie_cv_hip_avmm_0_hip_pipe_phystatus0>),                 //                                       .phystatus0
		.pcie_cv_hip_avmm_0_hip_pipe_phystatus1                 (<connected-to-pcie_cv_hip_avmm_0_hip_pipe_phystatus1>),                 //                                       .phystatus1
		.pcie_cv_hip_avmm_0_hip_pipe_phystatus2                 (<connected-to-pcie_cv_hip_avmm_0_hip_pipe_phystatus2>),                 //                                       .phystatus2
		.pcie_cv_hip_avmm_0_hip_pipe_phystatus3                 (<connected-to-pcie_cv_hip_avmm_0_hip_pipe_phystatus3>),                 //                                       .phystatus3
		.pcie_cv_hip_avmm_0_hip_pipe_rxdata0                    (<connected-to-pcie_cv_hip_avmm_0_hip_pipe_rxdata0>),                    //                                       .rxdata0
		.pcie_cv_hip_avmm_0_hip_pipe_rxdata1                    (<connected-to-pcie_cv_hip_avmm_0_hip_pipe_rxdata1>),                    //                                       .rxdata1
		.pcie_cv_hip_avmm_0_hip_pipe_rxdata2                    (<connected-to-pcie_cv_hip_avmm_0_hip_pipe_rxdata2>),                    //                                       .rxdata2
		.pcie_cv_hip_avmm_0_hip_pipe_rxdata3                    (<connected-to-pcie_cv_hip_avmm_0_hip_pipe_rxdata3>),                    //                                       .rxdata3
		.pcie_cv_hip_avmm_0_hip_pipe_rxdatak0                   (<connected-to-pcie_cv_hip_avmm_0_hip_pipe_rxdatak0>),                   //                                       .rxdatak0
		.pcie_cv_hip_avmm_0_hip_pipe_rxdatak1                   (<connected-to-pcie_cv_hip_avmm_0_hip_pipe_rxdatak1>),                   //                                       .rxdatak1
		.pcie_cv_hip_avmm_0_hip_pipe_rxdatak2                   (<connected-to-pcie_cv_hip_avmm_0_hip_pipe_rxdatak2>),                   //                                       .rxdatak2
		.pcie_cv_hip_avmm_0_hip_pipe_rxdatak3                   (<connected-to-pcie_cv_hip_avmm_0_hip_pipe_rxdatak3>),                   //                                       .rxdatak3
		.pcie_cv_hip_avmm_0_hip_pipe_rxelecidle0                (<connected-to-pcie_cv_hip_avmm_0_hip_pipe_rxelecidle0>),                //                                       .rxelecidle0
		.pcie_cv_hip_avmm_0_hip_pipe_rxelecidle1                (<connected-to-pcie_cv_hip_avmm_0_hip_pipe_rxelecidle1>),                //                                       .rxelecidle1
		.pcie_cv_hip_avmm_0_hip_pipe_rxelecidle2                (<connected-to-pcie_cv_hip_avmm_0_hip_pipe_rxelecidle2>),                //                                       .rxelecidle2
		.pcie_cv_hip_avmm_0_hip_pipe_rxelecidle3                (<connected-to-pcie_cv_hip_avmm_0_hip_pipe_rxelecidle3>),                //                                       .rxelecidle3
		.pcie_cv_hip_avmm_0_hip_pipe_rxstatus0                  (<connected-to-pcie_cv_hip_avmm_0_hip_pipe_rxstatus0>),                  //                                       .rxstatus0
		.pcie_cv_hip_avmm_0_hip_pipe_rxstatus1                  (<connected-to-pcie_cv_hip_avmm_0_hip_pipe_rxstatus1>),                  //                                       .rxstatus1
		.pcie_cv_hip_avmm_0_hip_pipe_rxstatus2                  (<connected-to-pcie_cv_hip_avmm_0_hip_pipe_rxstatus2>),                  //                                       .rxstatus2
		.pcie_cv_hip_avmm_0_hip_pipe_rxstatus3                  (<connected-to-pcie_cv_hip_avmm_0_hip_pipe_rxstatus3>),                  //                                       .rxstatus3
		.pcie_cv_hip_avmm_0_hip_pipe_rxvalid0                   (<connected-to-pcie_cv_hip_avmm_0_hip_pipe_rxvalid0>),                   //                                       .rxvalid0
		.pcie_cv_hip_avmm_0_hip_pipe_rxvalid1                   (<connected-to-pcie_cv_hip_avmm_0_hip_pipe_rxvalid1>),                   //                                       .rxvalid1
		.pcie_cv_hip_avmm_0_hip_pipe_rxvalid2                   (<connected-to-pcie_cv_hip_avmm_0_hip_pipe_rxvalid2>),                   //                                       .rxvalid2
		.pcie_cv_hip_avmm_0_hip_pipe_rxvalid3                   (<connected-to-pcie_cv_hip_avmm_0_hip_pipe_rxvalid3>),                   //                                       .rxvalid3
		.pcie_cv_hip_avmm_0_hip_serial_rx_in0                   (<connected-to-pcie_cv_hip_avmm_0_hip_serial_rx_in0>),                   //          pcie_cv_hip_avmm_0_hip_serial.rx_in0
		.pcie_cv_hip_avmm_0_hip_serial_rx_in1                   (<connected-to-pcie_cv_hip_avmm_0_hip_serial_rx_in1>),                   //                                       .rx_in1
		.pcie_cv_hip_avmm_0_hip_serial_rx_in2                   (<connected-to-pcie_cv_hip_avmm_0_hip_serial_rx_in2>),                   //                                       .rx_in2
		.pcie_cv_hip_avmm_0_hip_serial_rx_in3                   (<connected-to-pcie_cv_hip_avmm_0_hip_serial_rx_in3>),                   //                                       .rx_in3
		.pcie_cv_hip_avmm_0_hip_serial_tx_out0                  (<connected-to-pcie_cv_hip_avmm_0_hip_serial_tx_out0>),                  //                                       .tx_out0
		.pcie_cv_hip_avmm_0_hip_serial_tx_out1                  (<connected-to-pcie_cv_hip_avmm_0_hip_serial_tx_out1>),                  //                                       .tx_out1
		.pcie_cv_hip_avmm_0_hip_serial_tx_out2                  (<connected-to-pcie_cv_hip_avmm_0_hip_serial_tx_out2>),                  //                                       .tx_out2
		.pcie_cv_hip_avmm_0_hip_serial_tx_out3                  (<connected-to-pcie_cv_hip_avmm_0_hip_serial_tx_out3>),                  //                                       .tx_out3
		.pcie_cv_hip_avmm_0_npor_npor                           (<connected-to-pcie_cv_hip_avmm_0_npor_npor>),                           //                pcie_cv_hip_avmm_0_npor.npor
		.pcie_cv_hip_avmm_0_npor_pin_perst                      (<connected-to-pcie_cv_hip_avmm_0_npor_pin_perst>),                      //                                       .pin_perst
		.pcie_cv_hip_avmm_0_reconfig_clk_locked_fixedclk_locked (<connected-to-pcie_cv_hip_avmm_0_reconfig_clk_locked_fixedclk_locked>), // pcie_cv_hip_avmm_0_reconfig_clk_locked.fixedclk_locked
		.pcie_cv_hip_avmm_0_refclk_clk                          (<connected-to-pcie_cv_hip_avmm_0_refclk_clk>),                          //              pcie_cv_hip_avmm_0_refclk.clk
		.pio_coder_rst_external_connection_export               (<connected-to-pio_coder_rst_external_connection_export>),               //      pio_coder_rst_external_connection.export
		.pio_encoder_start_external_connection_export           (<connected-to-pio_encoder_start_external_connection_export>)            //  pio_encoder_start_external_connection.export
	);

